/**
 * SSR endpoint: `/cv.pdf` — Spanish CV (default locale).
 *
 * Built with Astro's `APIRoute` handler so it works in `server` mode
 * (configured via `@astrojs/node` standalone). The endpoint streams the
 * PDF generated by {@link renderCV} as `application/pdf`.
 */
import type { APIRoute } from "astro";

import { renderCV } from "../lib/cv-pdf";

export const prerender = false;

export const GET: APIRoute = async () => {
  const buffer = await renderCV("es");
  return new Response(buffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'inline; filename="sebastian-rodriguez-cv.pdf"',
      "Cache-Control": "public, max-age=3600",
    },
  });
};
